//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coronavirus_Aplicacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciudadano
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ciudadano()
        {
            this.estado_ciudadano = new HashSet<estado_ciudadano>();
            this.triaje = new HashSet<triaje>();
        }
    
        public int idciudadano { get; set; }
        public string nomciudadano { get; set; }
        public string apeciudadano { get; set; }
        public string celciudadano { get; set; }
        public int edadciudadano { get; set; }
        public int docciudadano { get; set; }
        public string dirciudadano { get; set; }
        public int iddepartamento { get; set; }
        public int idprov { get; set; }
        public int iddistrito { get; set; }
        public int idtipodocumento { get; set; }
        public System.DateTime fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estado_ciudadano> estado_ciudadano { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual distrito distrito { get; set; }
        public virtual provincia provincia { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<triaje> triaje { get; set; }
    }
}
