//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coronavirus_Aplicacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_CIUDADANO
    {
        public int id { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string docCiudadano { get; set; }
        public Nullable<int> idTriaje { get; set; }
    
        public virtual CIUDADANO CIUDADANO { get; set; }
        public virtual TIPO_ESTADO TIPO_ESTADO { get; set; }
        public virtual TRIAJE TRIAJE { get; set; }
    }
}
