//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coronavirus_Aplicacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_ciudadano
    {
        public int id { get; set; }
        public Nullable<int> idestado { get; set; }
        public string docciudadano { get; set; }
        public Nullable<int> idtriaje { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    
        public virtual ciudadano ciudadano { get; set; }
        public virtual tipo_estado tipo_estado { get; set; }
        public virtual triaje triaje { get; set; }
    }
}
