//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coronavirus_Aplicacion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sars_cov_2Entities1 : DbContext
    {
        public sars_cov_2Entities1()
            : base("name=sars_cov_2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciudadano> ciudadano { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<distrito> distrito { get; set; }
        public virtual DbSet<estado_ciudadano> estado_ciudadano { get; set; }
        public virtual DbSet<modulo> modulo { get; set; }
        public virtual DbSet<operacion> operacion { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<prueba> prueba { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rol_operacion> rol_operacion { get; set; }
        public virtual DbSet<suv> suv { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<tipo_estado> tipo_estado { get; set; }
        public virtual DbSet<triaje> triaje { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual int add_status_ciu(Nullable<int> idstatus, string doc, Nullable<int> triaje)
        {
            var idstatusParameter = idstatus.HasValue ?
                new ObjectParameter("idstatus", idstatus) :
                new ObjectParameter("idstatus", typeof(int));
    
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            var triajeParameter = triaje.HasValue ?
                new ObjectParameter("triaje", triaje) :
                new ObjectParameter("triaje", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_status_ciu", idstatusParameter, docParameter, triajeParameter);
        }
    
        public virtual int put_status_ciu(Nullable<int> idstatus, string doc)
        {
            var idstatusParameter = idstatus.HasValue ?
                new ObjectParameter("idstatus", idstatus) :
                new ObjectParameter("idstatus", typeof(int));
    
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("put_status_ciu", idstatusParameter, docParameter);
        }
    
        public virtual int sp_add_cuixtriaje(string nom, string ape, string cel, Nullable<int> edad, string doc, string dir, Nullable<int> depa, Nullable<int> prov, Nullable<int> dis, Nullable<int> tdoc, Nullable<System.DateTime> fecha, Nullable<bool> qua1, Nullable<bool> qua2, Nullable<bool> qua3, Nullable<bool> qua4, Nullable<bool> qua5, Nullable<bool> qua_obe, Nullable<bool> qua_enfe, Nullable<bool> qua_dia, Nullable<bool> qua_hipe, Nullable<bool> qua_can, Nullable<bool> qua_adu, Nullable<bool> qua_ni, Nullable<bool> qua_ges, Nullable<bool> qua_cro, Nullable<int> per)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var celParameter = cel != null ?
                new ObjectParameter("cel", cel) :
                new ObjectParameter("cel", typeof(string));
    
            var edadParameter = edad.HasValue ?
                new ObjectParameter("edad", edad) :
                new ObjectParameter("edad", typeof(int));
    
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var depaParameter = depa.HasValue ?
                new ObjectParameter("depa", depa) :
                new ObjectParameter("depa", typeof(int));
    
            var provParameter = prov.HasValue ?
                new ObjectParameter("prov", prov) :
                new ObjectParameter("prov", typeof(int));
    
            var disParameter = dis.HasValue ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(int));
    
            var tdocParameter = tdoc.HasValue ?
                new ObjectParameter("tdoc", tdoc) :
                new ObjectParameter("tdoc", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var qua1Parameter = qua1.HasValue ?
                new ObjectParameter("qua1", qua1) :
                new ObjectParameter("qua1", typeof(bool));
    
            var qua2Parameter = qua2.HasValue ?
                new ObjectParameter("qua2", qua2) :
                new ObjectParameter("qua2", typeof(bool));
    
            var qua3Parameter = qua3.HasValue ?
                new ObjectParameter("qua3", qua3) :
                new ObjectParameter("qua3", typeof(bool));
    
            var qua4Parameter = qua4.HasValue ?
                new ObjectParameter("qua4", qua4) :
                new ObjectParameter("qua4", typeof(bool));
    
            var qua5Parameter = qua5.HasValue ?
                new ObjectParameter("qua5", qua5) :
                new ObjectParameter("qua5", typeof(bool));
    
            var qua_obeParameter = qua_obe.HasValue ?
                new ObjectParameter("qua_obe", qua_obe) :
                new ObjectParameter("qua_obe", typeof(bool));
    
            var qua_enfeParameter = qua_enfe.HasValue ?
                new ObjectParameter("qua_enfe", qua_enfe) :
                new ObjectParameter("qua_enfe", typeof(bool));
    
            var qua_diaParameter = qua_dia.HasValue ?
                new ObjectParameter("qua_dia", qua_dia) :
                new ObjectParameter("qua_dia", typeof(bool));
    
            var qua_hipeParameter = qua_hipe.HasValue ?
                new ObjectParameter("qua_hipe", qua_hipe) :
                new ObjectParameter("qua_hipe", typeof(bool));
    
            var qua_canParameter = qua_can.HasValue ?
                new ObjectParameter("qua_can", qua_can) :
                new ObjectParameter("qua_can", typeof(bool));
    
            var qua_aduParameter = qua_adu.HasValue ?
                new ObjectParameter("qua_adu", qua_adu) :
                new ObjectParameter("qua_adu", typeof(bool));
    
            var qua_niParameter = qua_ni.HasValue ?
                new ObjectParameter("qua_ni", qua_ni) :
                new ObjectParameter("qua_ni", typeof(bool));
    
            var qua_gesParameter = qua_ges.HasValue ?
                new ObjectParameter("qua_ges", qua_ges) :
                new ObjectParameter("qua_ges", typeof(bool));
    
            var qua_croParameter = qua_cro.HasValue ?
                new ObjectParameter("qua_cro", qua_cro) :
                new ObjectParameter("qua_cro", typeof(bool));
    
            var perParameter = per.HasValue ?
                new ObjectParameter("per", per) :
                new ObjectParameter("per", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_cuixtriaje", nomParameter, apeParameter, celParameter, edadParameter, docParameter, dirParameter, depaParameter, provParameter, disParameter, tdocParameter, fechaParameter, qua1Parameter, qua2Parameter, qua3Parameter, qua4Parameter, qua5Parameter, qua_obeParameter, qua_enfeParameter, qua_diaParameter, qua_hipeParameter, qua_canParameter, qua_aduParameter, qua_niParameter, qua_gesParameter, qua_croParameter, perParameter);
        }
    
        public virtual ObjectResult<sp_list_ubigeo_Result> sp_list_ubigeo(string depa, string prov, string distri)
        {
            var depaParameter = depa != null ?
                new ObjectParameter("depa", depa) :
                new ObjectParameter("depa", typeof(string));
    
            var provParameter = prov != null ?
                new ObjectParameter("prov", prov) :
                new ObjectParameter("prov", typeof(string));
    
            var distriParameter = distri != null ?
                new ObjectParameter("distri", distri) :
                new ObjectParameter("distri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_list_ubigeo_Result>("sp_list_ubigeo", depaParameter, provParameter, distriParameter);
        }
    }
}
