-- MySQL Script generated by MySQL Workbench
-- 05/20/20 16:24:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sars_cov_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sars_cov_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sars_cov_2` DEFAULT CHARACTER SET utf8 ;
USE `sars_cov_2` ;

-- -----------------------------------------------------
-- Table `sars_cov_2`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`departamento` (
  `iddepartamento` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripdepa` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`iddepartamento`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`iddepartamento` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`provincia` (
  `idprov` INT(11) NOT NULL COMMENT '',
  `provincia` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `iddepa` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idprov`)  COMMENT '',
  INDEX `fk_iddepa` (`iddepa` ASC)  COMMENT '',
  CONSTRAINT `fk_iddepa`
    FOREIGN KEY (`iddepa`)
    REFERENCES `sars_cov_2`.`departamento` (`iddepartamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`distrito` (
  `iddistrito` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `distrito` VARCHAR(50) NOT NULL COMMENT '',
  `idprov` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`iddistrito`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`iddistrito` ASC)  COMMENT '',
  INDEX `fk_idprov` (`idprov` ASC)  COMMENT '',
  CONSTRAINT `fk_idprov`
    FOREIGN KEY (`idprov`)
    REFERENCES `sars_cov_2`.`provincia` (`idprov`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`tipo_documento` (
  `idtipodocumento` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `destipodocumento` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idtipodocumento`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`idtipodocumento` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`ciudadano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`ciudadano` (
  `idciudadano` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nomciudadano` VARCHAR(45) NOT NULL COMMENT '',
  `apeciudadano` VARCHAR(45) NOT NULL COMMENT '',
  `celciudadano` CHAR(9) NOT NULL COMMENT '',
  `edadciudadano` INT(11) NOT NULL COMMENT '',
  `docciudadano` CHAR(20) NOT NULL COMMENT '',
  `dirciudadano` VARCHAR(100) NOT NULL COMMENT '',
  `iddepartamento` INT(11) NOT NULL COMMENT '',
  `idprov` INT(11) NOT NULL COMMENT '',
  `iddistrito` INT(11) NOT NULL COMMENT '',
  `idtipodocumento` INT(11) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`docciudadano`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`idciudadano` ASC)  COMMENT '',
  INDEX `fk_iddepartamento` (`iddepartamento` ASC)  COMMENT '',
  INDEX `fk_iddistri` (`iddistrito` ASC)  COMMENT '',
  INDEX `fk_idprovi` (`idprov` ASC)  COMMENT '',
  INDEX `fk_idtipodocumento` (`idtipodocumento` ASC)  COMMENT '',
  CONSTRAINT `fk_iddepartamento`
    FOREIGN KEY (`iddepartamento`)
    REFERENCES `sars_cov_2`.`departamento` (`iddepartamento`),
  CONSTRAINT `fk_iddistri`
    FOREIGN KEY (`iddistrito`)
    REFERENCES `sars_cov_2`.`distrito` (`iddistrito`),
  CONSTRAINT `fk_idprovi`
    FOREIGN KEY (`idprov`)
    REFERENCES `sars_cov_2`.`provincia` (`idprov`),
  CONSTRAINT `fk_idtipodocumento`
    FOREIGN KEY (`idtipodocumento`)
    REFERENCES `sars_cov_2`.`tipo_documento` (`idtipodocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`tipo_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`tipo_estado` (
  `idestado` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `estado` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`idestado`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`idestado` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`triaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`triaje` (
  `idtriaje` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `question1` BIT(1) NOT NULL COMMENT '',
  `question2` BIT(1) NOT NULL COMMENT '',
  `question3` BIT(1) NOT NULL COMMENT '',
  `question4` BIT(1) NOT NULL COMMENT '',
  `question5` BIT(1) NOT NULL COMMENT '',
  `question_obesidad` BIT(1) NOT NULL COMMENT '',
  `question_enfermedad` BIT(1) NOT NULL COMMENT '',
  `question_diabetes` BIT(1) NOT NULL COMMENT '',
  `question_hipertension` BIT(1) NOT NULL COMMENT '',
  `question_cancer` BIT(1) NOT NULL COMMENT '',
  `question2_adulto` BIT(1) NOT NULL COMMENT '',
  `question2_nino` BIT(1) NOT NULL COMMENT '',
  `question2_gestante` BIT(1) NOT NULL COMMENT '',
  `question2_cronica` BIT(1) NOT NULL COMMENT '',
  `persona` INT(11) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `docciudadano` CHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`idtriaje`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`idtriaje` ASC)  COMMENT '',
  INDEX `fk_docciudadano` (`docciudadano` ASC)  COMMENT '',
  CONSTRAINT `fk_docciudadano`
    FOREIGN KEY (`docciudadano`)
    REFERENCES `sars_cov_2`.`ciudadano` (`docciudadano`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`estado_ciudadano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`estado_ciudadano` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idestado` INT(11) NULL DEFAULT NULL COMMENT '',
  `docciudadano` CHAR(20) NULL DEFAULT NULL COMMENT '',
  `idtriaje` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`id` ASC)  COMMENT '',
  INDEX `fk__estado_ci__docci__7a672e12` (`docciudadano` ASC)  COMMENT '',
  INDEX `fk__estado_ci__idest__440b1d61` (`idestado` ASC)  COMMENT '',
  INDEX `fk__estado_ci__idtri__7b5b524b` (`idtriaje` ASC)  COMMENT '',
  CONSTRAINT `fk__estado_ci__docci__7a672e12`
    FOREIGN KEY (`docciudadano`)
    REFERENCES `sars_cov_2`.`ciudadano` (`docciudadano`),
  CONSTRAINT `fk__estado_ci__idest__440b1d61`
    FOREIGN KEY (`idestado`)
    REFERENCES `sars_cov_2`.`tipo_estado` (`idestado`),
  CONSTRAINT `fk__estado_ci__idtri__7b5b524b`
    FOREIGN KEY (`idtriaje`)
    REFERENCES `sars_cov_2`.`triaje` (`idtriaje`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`modulo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`operacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `idmodulo` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`id` ASC)  COMMENT '',
  INDEX `fk__operacion__idmod__45f365d3` (`idmodulo` ASC)  COMMENT '',
  CONSTRAINT `fk__operacion__idmod__45f365d3`
    FOREIGN KEY (`idmodulo`)
    REFERENCES `sars_cov_2`.`modulo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`prueba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`prueba` (
  `id` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`rol_operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`rol_operacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idrol` INT(11) NULL DEFAULT NULL COMMENT '',
  `idoperacion` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`id` ASC)  COMMENT '',
  INDEX `fk__rol_opera__idope__47dbae45` (`idoperacion` ASC)  COMMENT '',
  INDEX `fk__rol_opera__idrol__48cfd27e` (`idrol` ASC)  COMMENT '',
  CONSTRAINT `fk__rol_opera__idope__47dbae45`
    FOREIGN KEY (`idoperacion`)
    REFERENCES `sars_cov_2`.`operacion` (`id`),
  CONSTRAINT `fk__rol_opera__idrol__48cfd27e`
    FOREIGN KEY (`idrol`)
    REFERENCES `sars_cov_2`.`rol` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`suv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`suv` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`id` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sars_cov_2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sars_cov_2`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(200) NOT NULL COMMENT '',
  `password` VARCHAR(200) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `idrol` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `ix_tmp_autoinc` (`id` ASC)  COMMENT '',
  INDEX `fk__usuario__idrol__4ab81af0` (`idrol` ASC)  COMMENT '',
  CONSTRAINT `fk__usuario__idrol__4ab81af0`
    FOREIGN KEY (`idrol`)
    REFERENCES `sars_cov_2`.`rol` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
